baseURL = "https://cyla-app.github.io/"
languageCode = "de-DE"
title = "Cyla"
theme = "hallo"
defaultContentLanguage = "de"

[Author]
    name = "Cyla"

[params]
    greeting = "Hallo."
    [[params.links]]
        icon = "github"
        title = "Github"
        url = "https://github.com/cyla-app"

    [[params.links]]
        iconset = "fas"
        icon = "envelope"
        title = "E-mail"
        url = "mailto:max@maxammann.org"
